### ISSUE TITLE
Seaside 2nd Edition - Update Pack

### ISSUE THREAD

**Issue by O491dogan** [poet-of-the-fall/carddivider#28]
Hi!
First of all - thank you for your amazing work and maintaining all the expansions!

I have recently bought the small update pack for the seaside expansion (first edition, HIG2009) to have the new cards of the 2nd edition. 
I would like to kindly ask, if you could add another section within your dividers for only the cards of the update pack (the new ones of the 2nd edition).

https://spieltraum-shop.de/unser-sortiment/spiele/kenner/14670/dominion-seaside-2.-edition-update-pack/

Thank you!

Edit: Wait - I've just discovered the corresponding tex file. It's currently not enabled in the main file. Is this on purpose?

**Comment by poet-of-the-fall** [comment]
Hi @O491dogan,

the .tex file is already there as a placeholder, because I did not have the game instructions of the update pack when I added the second edition of Seaside. 
Unfortunately this one is not on the dominion website and Amazon is not listing it yet. But I already saw it in other shops and will order it soon. Alternatively you can just send me pictures of every page of the instructions so that I can do the fine tuning on that one...or - if sufficient - just uncomment the Tex import and build it again to get the dividers for the update pack 😊

**Comment by O491dogan** [comment]
Thank you for your fast reply! :-)
Speaking of the update pack, there aren't any instructions coming with it. Just one empty card and an updated sorting strip.
I guess I'm just going to wait a bit more! ;-)
I'm currently reworking our storage box and I have to order some paper - so there's enough time to wait and also winter is coming.
Thanks again!

**Comment by poet-of-the-fall** [comment]
Thanks @O491dogan, if there is no additional instruction in the box we just take the ones from the 2. Edition. I created the new files, so all should be present now 😊
